// filepath: /home/colin/hackathons_local/ambank_2025/teamteam/src/lib/mock-data.ts
import type { Issue } from "@/types/issue"

export const mockIssues: Issue[] = [
  {
    id: "SR3349140",
    ticketTitle: "Inconsistent Customer Data Format",
    description: "Customer names appearing in different formats across systems",
    priority: "High",
    status: "new",
    requesterName: "John Doe",
    requesterContact: "+60123456789",
    requesterDepartment: "IT",
    requesterUnit: "Data Management",
    sourceSystem: "Core Banking",
    impactedArea: "Customer Database",
    createdAt: new Date("2024-01-15"),
    assignedAt: new Date("2024-01-16"),
    deadline: new Date("2024-02-15"),
    createdByUid: "user1",
    dqPicUid: "",
    itPicUid: "",
    mediaAttachments: [],
    dqIssueCategory: "Inconsistent value",
    problemCategory: "Data Format Issues",
    isRecurring: true,
    reportedRecordTotal: 1500,
    impactedRecordTotal: 1200,
    cleansedRecordTotal: 800,
    aiSuggestions: {
      impactScore: 4,
      complexityScore: 3,
      totalScore: 7,
      suggestedPriority: "High",
    },
  },
  {
    id: "SR3349141",
    ticketTitle: "Missing Transaction Records",
    description: "Some transaction records are not appearing in daily reports",
    priority: "Medium",
    status: "in_progress",
    requesterName: "Jane Smith",
    requesterContact: "+60123456788",
    requesterDepartment: "Operations",
    requesterUnit: "Transaction Processing",
    sourceSystem: "Payment Gateway",
    impactedArea: "Transaction Reports",
    createdAt: new Date("2024-01-10"),
    assignedAt: new Date("2024-01-11"),
    deadline: new Date("2024-02-10"),
    createdByUid: "user2",
    dqPicUid: "steward1",
    itPicUid: "it1",
    mediaAttachments: [],
    dqIssueCategory: "Blank value",
    problemCategory: "Data Completeness",
    isRecurring: false,
    reportedRecordTotal: 500,
    impactedRecordTotal: 50,
    cleansedRecordTotal: 0,
    resolutionCategory: "Manual Data Cleansing",
    aiSuggestions: {
      impactScore: 3,
      complexityScore: 2,
      totalScore: 5,
      suggestedPriority: "Medium",
    },
  },
  {
    id: "SR3349142",
    ticketTitle: "Duplicate Account Entries",
    description: "Multiple account entries found for the same customer",
    priority: "Low",
    status: "monitoring",
    requesterName: "Mike Johnson",
    requesterContact: "+60123456787",
    requesterDepartment: "Customer Service",
    requesterUnit: "Account Management",
    sourceSystem: "CRM System",
    impactedArea: "Customer Accounts",
    createdAt: new Date("2024-01-05"),
    assignedAt: new Date("2024-01-06"),
    deadline: new Date("2024-02-05"),
    createdByUid: "user3",
    dqPicUid: "steward1",
    itPicUid: "it2",
    mediaAttachments: [],
    dqIssueCategory: "Duplicate value",
    problemCategory: "Data Duplication",
    isRecurring: true,
    reportedRecordTotal: 200,
    impactedRecordTotal: 100,
    cleansedRecordTotal: 90,
    resolutionCategory: "Software Improvement",
    aiSuggestions: {
      impactScore: 2,
      complexityScore: 2,
      totalScore: 4,
      suggestedPriority: "Low",
    },
  },
  {
    id: "SR3349143",
    ticketTitle: "Invalid Date Formats in Reports",
    description: "Date fields showing inconsistent formats across different reports",
    priority: "Medium",
    status: "in_progress",
    requesterName: "Sarah Wilson",
    requesterContact: "+60123456786",
    requesterDepartment: "Finance",
    requesterUnit: "Reporting",
    sourceSystem: "Financial System",
    impactedArea: "Financial Reports",
    createdAt: new Date("2024-01-12"),
    assignedAt: new Date("2024-01-13"),
    deadline: new Date("2024-02-12"),
    createdByUid: "user4",
    dqPicUid: "steward2",
    itPicUid: "it3",
    mediaAttachments: [],
    dqIssueCategory: "Invalid value",
    problemCategory: "Date Format Issues",
    isRecurring: false,
    reportedRecordTotal: 800,
    impactedRecordTotal: 600,
    cleansedRecordTotal: 300,
    resolutionCategory: "Process Improvement",
    aiSuggestions: {
      impactScore: 3,
      complexityScore: 3,
      totalScore: 6,
      suggestedPriority: "Medium",
    },
  },
  {
    id: "SR3349144",
    ticketTitle: "Blank Customer Phone Numbers",
    description: "Many customer records have missing phone number information",
    priority: "High",
    status: "new",
    requesterName: "David Chen",
    requesterContact: "+60123456785",
    requesterDepartment: "Customer Service",
    requesterUnit: "Data Quality",
    sourceSystem: "Customer Database",
    impactedArea: "Customer Contact Info",
    createdAt: new Date("2024-01-18"),
    assignedAt: new Date("2024-01-19"),
    deadline: new Date("2024-02-18"),
    createdByUid: "user5",
    dqPicUid: "",
    itPicUid: "",
    mediaAttachments: [],
    dqIssueCategory: "Blank value",
    problemCategory: "Missing Contact Information",
    isRecurring: true,
    reportedRecordTotal: 2000,
    impactedRecordTotal: 1800,
    cleansedRecordTotal: 0,
    aiSuggestions: {
      impactScore: 4,
      complexityScore: 2,
      totalScore: 6,
      suggestedPriority: "High",
    },
  },
]