// filepath: /home/colin/hackathons_local/ambank_2025/teamteam/src/lib/mock-data.ts
import type { Issue } from "@/types/issue"

export const mockIssues: Issue[] = [
  {
    id: "SR3349151",
    ticketTitle: "Mismatch in Account Opening Dates",
    status: "new",
    description: "Customer account opening dates differ across modules.",
    requesterName: "Lisa Ong",
    requesterDepartment: "Operations",
    requesterContact: "+60123456001",
    requesterCostCenter: "OPS123",
    requesterUnit: "Customer Onboarding",
    requesterTeamLeader: "Tan Wei Jian",
    sourceSystem: "Core Banking",
    impactedArea: "Customer Master",
    otherPIC: "audit@ambank.com",
    suggestedResolution: "Sync date fields using master record.",
    mediaAttachment: [],
    dataClass: "KYC",
    cde: "Yes",
    issueCategory: "Inconsistent value",
    issueField: "OpenDate",
    rcaCategory: "Processes",
    rcaDetails: "Manual override by staff on exception",
    impactAnalysis: "Regulatory non-compliance risk",
    remarks: "",
    notes: "",
    priority: "High",
    impactScore: 5,
    complexityScore: 3,
    totalScore: 8,
    workingDays: 30,
    suggestedPriority: "High",
    dqPicUid: "",
    dsPicUid: "",
    createdAt: new Date("2024-06-15"),
    pickedUpAt: null,
    assignedAt: null,
    resolvedAt: null,
    completedAt: null,
    agingDays: 44,
    agingMonths: 1,
    agingBucket: "0-6 months",
    reportedTotal: 1000,
    impactedTotal: 800,
    cleansedTotal: 200,
    excludedTotal: 100,
    outstandingTotal: 500,
    percentTotal: "25%",
  },
  {
    id: "SR3349152",
    ticketTitle: "Duplicate Transaction IDs",
    status: "in_progress",
    description: "Transaction IDs are duplicated due to concurrent processing.",
    requesterName: "Afiq Zainal",
    requesterDepartment: "IT",
    requesterContact: "+60123456002",
    requesterCostCenter: "IT456",
    requesterUnit: "Payments",
    requesterTeamLeader: "Rashid Ahmad",
    sourceSystem: "Payment Gateway",
    impactedArea: "Transaction Logs",
    otherPIC: "fraud@ambank.com",
    suggestedResolution: "Implement UUID generator logic.",
    mediaAttachment: [],
    dataClass: "Transaction",
    cde: "No",
    issueCategory: "Duplicate value",
    issueField: "TransactionID",
    rcaCategory: "Technology",
    rcaDetails: "Race condition in legacy service",
    impactAnalysis: "Incorrect balances and reconciliation errors",
    remarks: "Needs patch before end of Q3",
    notes: "",
    priority: "Medium",
    impactScore: 3,
    complexityScore: 2,
    totalScore: 5,
    workingDays: 30,
    suggestedPriority: "Medium",
    dqPicUid: "steward3",
    dsPicUid: "ds1",
    createdAt: new Date("2024-07-01"),
    pickedUpAt: new Date("2024-07-02"),
    assignedAt: new Date("2024-07-03"),
    resolvedAt: null,
    completedAt: null,
    agingDays: 26,
    agingMonths: 0,
    agingBucket: "0-6 months",
    reportedTotal: 5000,
    impactedTotal: 300,
    cleansedTotal: 270,
    excludedTotal: 10,
    outstandingTotal: 20,
    percentTotal: "90%",
  },
  {
    id: "SR3349153",
    ticketTitle: "Blank Email Addresses",
    status: "monitoring",
    description: "Thousands of customer records missing email addresses.",
    requesterName: "Maya Lee",
    requesterDepartment: "Customer Service",
    requesterContact: "+60123456003",
    requesterCostCenter: "CS789",
    requesterUnit: "Support",
    requesterTeamLeader: "Ravi Menon",
    sourceSystem: "CRM",
    impactedArea: "Notifications",
    otherPIC: "itops@ambank.com",
    suggestedResolution: "Make email mandatory on input forms.",
    mediaAttachment: [],
    dataClass: "PII",
    cde: "Yes",
    issueCategory: "Blank value",
    issueField: "Email",
    rcaCategory: "Processes",
    rcaDetails: "Validation missing on legacy portal",
    impactAnalysis: "Unable to send e-statements",
    remarks: "",
    notes: "",
    priority: "Low",
    impactScore: 2,
    complexityScore: 2,
    totalScore: 4,
    workingDays: 15,
    suggestedPriority: "Low",
    dqPicUid: "steward2",
    dsPicUid: "ds2",
    createdAt: new Date("2023-12-01"),
    pickedUpAt: new Date("2023-12-05"),
    assignedAt: new Date("2023-12-06"),
    resolvedAt: new Date("2024-01-15"),
    completedAt: new Date("2024-02-01"),
    agingDays: 235,
    agingMonths: 8,
    agingBucket: "7-18 months",
    reportedTotal: 20000,
    impactedTotal: 5000,
    cleansedTotal: 3500,
    excludedTotal: 500,
    outstandingTotal: 1000,
    percentTotal: "70%",
  },
  {
    id: "SR3349154",
    ticketTitle: "Staff Login Records Missing",
    status: "rejected",
    description: "Missing logs for specific branches due to outage.",
    requesterName: "Daniel Tan",
    requesterDepartment: "Risk",
    requesterContact: "+60123456004",
    requesterCostCenter: "RISK001",
    requesterUnit: "Compliance",
    requesterTeamLeader: "Wong Yee Mun",
    sourceSystem: "Staff Portal",
    impactedArea: "Audit Trail",
    otherPIC: "secops@ambank.com",
    suggestedResolution: "Backfill logs from backup server",
    mediaAttachment: [],
    dataClass: "Internal Ops",
    cde: "No",
    issueCategory: "Blank value",
    issueField: "LoginTime",
    rcaCategory: "Technology",
    rcaDetails: "Log collector failed during system patch",
    impactAnalysis: "Audit risk during review",
    remarks: "Ops team refused action due to low impact",
    notes: "Consider secondary log stream pipeline",
    priority: "Low",
    impactScore: 1,
    complexityScore: 1,
    totalScore: 2,
    workingDays: 15,
    suggestedPriority: "Low",
    dqPicUid: "",
    dsPicUid: "",
    createdAt: new Date("2023-01-01"),
    pickedUpAt: new Date("2023-01-03"),
    assignedAt: new Date("2023-01-04"),
    resolvedAt: null,
    completedAt: null,
    agingDays: 576,
    agingMonths: 19,
    agingBucket: ">18 months",
    reportedTotal: 500,
    impactedTotal: 450,
    cleansedTotal: 0,
    excludedTotal: 50,
    outstandingTotal: 400,
    percentTotal: "0%",
  },
  {
    id: "SR3349155",
    ticketTitle: "Foreign Characters in Customer Names",
    status: "closed",
    description: "Some names saved in corrupted encoding (e.g. mojibake).",
    requesterName: "Chong Mei Hui",
    requesterDepartment: "IT",
    requesterContact: "+60123456005",
    requesterCostCenter: "IT789",
    requesterUnit: "Core Apps",
    requesterTeamLeader: "Lim Hao Wen",
    sourceSystem: "Customer Master",
    impactedArea: "Name Field",
    otherPIC: "",
    suggestedResolution: "Apply UTF-8 enforcement across pipeline.",
    mediaAttachment: ["mojibake-sample.png"],
    dataClass: "PII",
    cde: "Yes",
    issueCategory: "Invalid value",
    issueField: "Name",
    rcaCategory: "Technology",
    rcaDetails: "Encoding mismatch between ETL stages",
    impactAnalysis: "Inaccurate KYC records for foreign nationals",
    remarks: "",
    notes: "",
    priority: "High",
    impactScore: 5,
    complexityScore: 5,
    totalScore: 10,
    workingDays: 60,
    suggestedPriority: "High",
    dqPicUid: "steward5",
    dsPicUid: "ds5",
    createdAt: new Date("2024-03-01"),
    pickedUpAt: new Date("2024-03-02"),
    assignedAt: new Date("2024-03-03"),
    resolvedAt: new Date("2024-05-01"),
    completedAt: new Date("2024-05-10"),
    agingDays: 148,
    agingMonths: 5,
    agingBucket: "0-6 months",
    reportedTotal: 1200,
    impactedTotal: 1000,
    cleansedTotal: 1000,
    excludedTotal: 0,
    outstandingTotal: 0,
    percentTotal: "100%",
  },
]
